---
- name: Create virtual hosts
  hosts: ms[0]
  gather_facts: no
  vars:
    org: opdk
    env: test
    property_folders:
    - "~/.apigee-secure"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-settings-region }
  - { role: apigee-opdk-settings-private-address }
  - { role: apigee-opdk-settings-management-server }

  tasks:
  - name: Create virtual hosts
    uri:
      url: "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org }}/e/{{ env }}/virtualhosts"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"
      method: POST
      src: vhost.json
