---
- name: Remove virtual hosts
  hosts: ms[0]
  gather_facts: no
  vars:
    org: VALIDATE
    env: dev
    property_folders:
    - "~/.apigee-secure"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-settings-region }
  - { role: apigee-opdk-settings-private-address }
  - { role: apigee-opdk-settings-management-server }

  tasks:
  - name: Obtain list of virtual hosts
    uri:
      url: "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org }}/e/{{ env }}/virtualhosts"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"
    register: list

  - name: Delete virtual hosts
    uri:
      url: "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org }}/e/{{ env }}/virtualhosts/{{ item }}"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"
      method: DELETE
    with_items: "{{ list.json }}"
