---
- name: Install Cassandra
  hosts: ds
  gather_facts: no
  serial: 1
  tags: ['ds']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-setup-component, profile: 'c' }