---
- name: Collect Configuration Information for Planet
  hosts: edge
  strategy: free
  tags: ['cache']
  vars:
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
  - apigee-opdk-modules
  - apigee-opdk-settings-private-address
  - apigee-opdk-settings-management-server
  - apigee-opdk-settings-region
  - apigee-opdk-settings-response-file
  - apigee-opdk-settings-ldap
  - apigee-opdk-settings-cassandra
  - apigee-opdk-settings-postgres


- name: Generate Configuration for Planet
  hosts: ms
  gather_facts: no
  strategy: free
  tags: ['response-file']
  vars:
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - apigee-opdk-settings-private-address
    - apigee-opdk-settings-management-server
    - apigee-opdk-settings-region
    - apigee-opdk-settings-ldap
    - apigee-opdk-setup-apigee-user
    - apigee-opdk-settings-cassandra
    - apigee-opdk-settings-postgres
    - apigee-opdk-setup-silent-installation-config

- name: Distribute Configuration File to Planet
  hosts: edge
  gather_facts: no
  strategy: free
  tags: ['copy']
  vars:
    property_folders:
    - "~/.apigee"
    - "~/.apigee-secure"
  roles:
    - { role: apigee-opdk-modules, tags: ['license'] }
    - apigee-opdk-setup-apigee-user
    - { role: apigee-opdk-setup-license, tags: ['license'] }
    - apigee-opdk-setup-apigee-user-ownership
  tasks:
    - name: Create Target Folder on Target Node
      become: yes
      file:
        path: "{{ target_response_file_path | dirname }}"
        state: directory
        mode: 777
        owner: '{{ opdk_user_name }}'
        group: '{{ opdk_group_name }}'

    - name: Distribute Configuration File
      become: yes
      copy:
        src: '{{ local_response_file_path }}'
        dest: "{{ target_response_file_path }}"
        owner: '{{ opdk_user_name }}'
        group: '{{ opdk_group_name }}'
        mode: 777

    - name: Assert Permissions are Correct
      become: yes
      file:
        path: "{{ target_response_file_path | dirname }}"
        recurse: yes
        mode: "777"
        owner: '{{ opdk_user_name }}'
        group: '{{ opdk_group_name }}'