---
- name: Destroy infrastructure
  hosts: localhost
  vars_prompt:
    - name: project_path
      prompt: "Which project do you want to build? ['5-node','aio','dev','prod']"
      default: "dev"
      private: no

    - name: gcp_credentials_file
      prompt: "Service Account Credentials File Path"
      default: "{{ '~/.apigee-secure/sandbox/sandbox-default-service-account.json' | expanduser }}"
      private: no

    - name: gcp_project_name
      prompt: "GCP Project Name"
      default: "sandbox-173316"
      private: no
    - name: default_region
      prompt: "Default Region"
      default: "us-east1"
      private: no

    - name: default_zone
      prompt: "Default Zone"
      default: "us-east1-b"
      private: no

  vars:
    terraform_state_file: "{{ playbook_dir }}/terraform.tfstate"
    terraform_workspace: "{{ playbook_dir }}"

  tasks:
    - name: Destroy infrastructure
      terraform:
        binary_path: "{{ playbook_dir }}/terraform"
        project_path: "{{ playbook_dir }}/{{ project_path }}"
        state: absent
        force_init: yes
        purge_workspace: yes
        variables:
          region: "{{ default_region }}"
          zone: "{{ default_zone }}"
          credentials_file: "{{ gcp_credentials_file }}"
          gcp_project_name: "{{ gcp_project_name }}"
