---
- name: Create infrastructure
  hosts: localhost
  vars_prompt:
    - name: project_path
      prompt: "Which project do you want to build? ['5-node','aio','dev','prod']"
      default: "dev"
      private: no

    - name: default_region
      prompt: "Default Region"
      default: "us-east1"
      private: no

    - name: default_zone
      prompt: "Default Zone"
      default: "us-east1-b"
      private: no

    - name: gcp_credentials_file
      prompt: "Service Account Credentials File Path"
      default: "{{ '~/.apigee-secure/sandbox/sandbox-default-service-account.json' | expanduser }}"
      private: no

    - name: gcp_project_name
      prompt: "GCP Project Name"
      default: "sandbox-173316"
      private: no

    - name: service_account_email
      prompt: "Service Account Email"
      default: "736255665193-compute@developer.gserviceaccount.com"
      private: no

  vars:
    terraform_version: "0.12.0"
    terraform_download_links:
      Debian: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
      MacOSX: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_darwin_amd64.zip"
    dc_1_ms_count: 1
    dc_2_ms_count: 1
    dc_1_ds_count: 3
    dc_2_ds_count: 3
    dc_1_rmp_count: 2
    dc_2_rmp_count: 2
    dc_1_qpid_count: 2
    dc_2_qpid_count: 2
    dc_1_pg_only_count: 0
    dc_1_pgmaster_count: 1
    dc_1_pgstandby_count: 0
    dc_2_pgstandby_count: 1
    dev_portal_count: 0

  tasks:
    - name: Install archive management packages
      become: true
      tags: ['system']
      apt:
        name: "unzip"
        state: present
      when: ansible_distribution == "Debian"

    - name: Install archive management packages on Mac
      tags: ['system']
      package:
        name: "unzip"
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Install archive management packages
      become: true
      tags: ['system']
      package:
        name: "unzip"
        state: present
      when: ansible_distribution != "MacOSX"

    - name: Set terraform link
      set_fact:
        terraform_download_link: "{{ terraform_download_links[ansible_distribution] }}"

    - name: Download Terraform binary
      get_url:
        url: "{{ terraform_download_link }}"
        dest: "./{{ terraform_download_link | basename }}"
        validate_certs: no

    - name: Unarchive terraform binary
      unarchive:
        src: "{{ terraform_download_link | basename }}"
        dest: ./
        remote_src: yes

    - name: Create infrastructure
      terraform:
        binary_path: "{{ playbook_dir }}/terraform"
        project_path: "{{ playbook_dir }}/{{ project_path }}"
        state: present
        force_init: yes
        variables:
          region: "{{ default_region }}"
          zone: "{{ default_zone }}"
          credentials_file: "{{ gcp_credentials_file }}"
          gcp_project_name: "{{ gcp_project_name }}"
          dc_1_ms_count: "{{ dc_1_ms_count }}"
          dc_2_ms_count: "{{ dc_2_ms_count }}"
          dc_1_ds_count: "{{ dc_1_ds_count }}"
          dc_2_ds_count: "{{ dc_2_ds_count }}"
          dc_1_rmp_count: "{{ dc_1_rmp_count }}"
          dc_2_rmp_count: "{{ dc_2_rmp_count }}"
          dc_1_qpid_count: "{{ dc_1_qpid_count }}"
          dc_2_qpid_count: "{{ dc_2_qpid_count }}"
          dc_1_pg_only_count: "{{ dc_1_pg_only_count }}"
          dc_1_pgmaster_count: "{{ dc_1_pgmaster_count }}"
          dc_1_pgstandby_count: "{{ dc_1_pgstandby_count }}"
          dc_2_pgstandby_count: "{{ dc_2_pgstandby_count }}"
          dev_portal_count: "{{ dev_portal_count }}"

