---
- name: Cassandra
  hosts: ds
  tags: ['ds']
  strategy: free
  tasks:
    - name: Status Cassandra
      command: 'removes=/opt/apigee/apigee-cassandra /opt/apigee/apigee-service/bin/apigee-service apigee-cassandra status'
      
- name: Zookeeper
  hosts: ds
  tags: ['zk']
  strategy: free
  tasks:
    - name: Status Zookeeper
      command: 'removes=/opt/apigee/apigee-zookeeper /opt/apigee/apigee-service/bin/apigee-service apigee-zookeeper status'

- name: Ldap
  hosts: ldap
  tags: ['ldap']
  strategy: free
  tasks:
    - name: Status Ldap
      command: '/opt/apigee/apigee-service/bin/apigee-service apigee-openldap status'
      
- name: Management Server
  hosts: ms
  tags: ['ms']
  strategy: free
  tasks:
    - name: Status Management Server
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-management-server status'

- name: Edge-UI
  hosts: ui
  tags: ['ui']
  strategy: free
  tasks:
    - name: Status UI
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-ui status'

- name: Router
  hosts: router,rmp
  tags: ['router','r']
  strategy: free
  tasks:
    - name: Status Router
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-router status'

- name: Message Processor
  hosts: mp,rmp
  tags: ['mp']
  strategy: free
  tasks:
    - name: Status Message Processor
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-message-processor status'
      
- name: Qpid
  hosts: qpid
  tags: ['qpid']
  strategy: free
  tasks:
    - name: Status Qpid
      command: '/opt/apigee/apigee-service/bin/apigee-service apigee-qpidd status'
    - name: Status Qpid Server
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-qpid-server status'
      
- name: Postgres
  hosts: pg
  tags: ['pg']
  strategy: free
  tasks:
    - name: Status Postgres
      command: '/opt/apigee/apigee-service/bin/apigee-service apigee-postgresql status'
    - name: Status Postgres Server
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-postgres-server status'