---
- name: Update local cache
  hosts: edge
  gather_facts: no
  tags: ['cache']
  vars:
    property_folders:
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules }
    - { role: apigee-opdk-setup-openjdk-cache, jdk_version: '1.8' }
    - { role: apigee-opdk-settings-private-address  }
    - { role: apigee-opdk-settings-management-server }
    - { role: apigee-opdk-settings-ldap  }
    - { role: apigee-opdk-settings-region }
    - { role: apigee-opdk-settings-cassandra }
    - { role: apigee-opdk-settings-postgres  }
    - { role: apigee-opdk-setup-bootstrap-cache }

- name: Remove virtual hosts
  hosts: ms[0]
  gather_facts: no
  vars:
    property_folders:
    - "~/.apigee-secure"
  roles:
  - { role: apigee-opdk-modules }

  tasks:

  - name: Assert the organization name
    assert:
      that:
      - org_name is defined and org_name | trim | length > 0
      msg: Please provide the organization name from which to remove all environments.

  - name: Obtain list of environments from org
    uri:
      url: "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org_name }}/e"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"
    register: list

  - name: Delete all environments from org
    uri:
      url: "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org_name }}/e/{{ item }}"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"
      method: DELETE
    with_items: "{{ list.json }}"
