---
- name: Collect server info into cache
  hosts: ms
  gather_facts: no
  roles:
  - apigee-opdk-modules
  - apigee-opdk-settings-region
  - apigee-opdk-settings-private-address
  - apigee-opdk-settings-management-server

- name: Configure Organization and Environments
  hosts: ms[0]
  serial: 1
  gather_facts: no
  tags: ['org']
  vars:
    org_name: '{org}'
    env_name: '{env}'
    virtual_host_name: '{name}'
    virtual_host_alias: '{dns}'
    virtual_host_port: '{port}'
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - apigee-opdk-setup-org