---
- name: Configure Organization and Environments
  hosts: ms[0]
  serial: 1
  gather_facts: no
  tags: ['org']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-setup-org, org_name: '{org}', env_name: '{env}', virtual_host_alias: '{dns}', virtual_host_port: '{port}', virtual_host_name: '{name}' }