---
- name: Validate that Management Server port requirements are met
  hosts: ms
  tags: ['ms']
  strategy: free
  vars:
    ports:
      - "{{ monit_ports }}"
  roles:
    - { role: apigee-opdk-port-check, host_list: "{{ groups['ms'] }}" }

- name: Validate that Openldap port requirements are met
  hosts: ldap
  tags: ['ldap']
  strategy: free
  vars:
    ports:
      - "{{ monit_ports }}"
  roles:
    - { role: apigee-opdk-port-check, host_list: "{{ groups['ldap'] }}" }


- name: Validate that Zookeeper port requirements are met
  hosts: ds
  tags: ['zk']
  strategy: free
  vars:
    ports:
      - "{{ monit_ports }}"
  roles:
    - { role: apigee-opdk-port-check, host_list: "{{ groups['zk'] }}" }

- name: Validate that Cassandra  port requirements are met
  hosts: ds
  tags: ['ds']
  strategy: free
  vars:
    ports:
      - "{{ monit_ports }}"
  roles:
    - { role: apigee-opdk-port-check, host_list: "{{ groups['ds'] }}" }

- name: Validate that Router port requirements are met
  hosts: rmp
  tags: ['router']
  strategy: free
  vars:
    ports:
      - "{{ monit_ports }}"
  roles:
    - { role: apigee-opdk-port-check, host_list: "{{ groups['rmp'] }}" }

- name: Validate that Message Processor port requirements are met
  hosts: rmp
  tags: ['mp']
  strategy: free
  vars:
    ports:
      - "{{ monit_ports }}"
  roles:
    - { role: apigee-opdk-port-check, host_list: "{{ groups['rmp'] }}" }

- name: Validate that Message Processor port requirements are met
  hosts: qpid
  tags: ['qpid']
  strategy: free
  vars:
    ports:
      - "{{ monit_ports }}"
  roles:
    - { role: apigee-opdk-port-check, host_list: "{{ groups['qpid'] }}" }

- name: Validate that Postgres port requirements are met
  hosts: pg
  tags: ['pg']
  strategy: free
  vars:
    ports:
      - "{{ monit_ports }}"
  roles:
    - { role: apigee-opdk-port-check, host_list: "{{ groups['pg'] }}" }