---
- name: Remove servers
  hosts: ms[0]
  gather_facts: no
  vars:
    org: VALIDATE
    env: dev
    pod: gateway
    property_folders:
    - "~/.apigee-secure"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-settings-region }
  - { role: apigee-opdk-settings-private-address }
  - { role: apigee-opdk-settings-management-server }

  tasks:
  - name: Obtain list of environments for organizations
    uri:
      url: "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org }}/e"
      user: "{{ opdk_user_email }}"
      password: "{{ opdk_user_pass }}"
    register: env_list

  - name: Obtain list of servers by environment
    include_tasks: delete-servers-by-environment.yml
    with_items: "{{ env_list.json }}"
    loop_control:
      loop_var: each_env

