---
- src: https://github.com/carlosfrias/apigee-opdk-backup.git

- src: https://github.com/carlosfrias/apigee-opdk-start-components.git

- src: https://github.com/carlosfrias/apigee-opdk-stop-components.git

- src: https://github.com/carlosfrias/apigee-opdk-setup-component.git

- src: https://github.com/carlosfrias/apigee-opdk-setup-bootstrap-rollback.git

- src: https://github.com/carlosfrias/apigee-opdk-server-self.git

- src: https://github.com/carlosfrias/apigee-opdk-modules.git

