---
- name: Cassandra & Zookeeper
  hosts: ds
  tags: ['ds','zk']
  strategy: free
  tasks:
    - name: Backup Cassandra
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service apigee-cassandra backup'
    - name: Backup Zookeeper
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service apigee-zookeeper backup'
      
- name: Ldap
  hosts: ldap
  tags: ['ldap']
  strategy: free
  tasks:
    - name: Backup Ldap
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service apigee-openldap backup'

- name: Management Server
  hosts: ms
  tags: ['ms']
  strategy: free
  tasks:
    - name: Backup Management Server
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-management-server backup'
      
- name: Edge-UI
  hosts: ui
  tags: ['ui']
  strategy: free
  tasks:
    - name: Backup UI
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-ui backup'
      
- name: Router
  hosts: router,rmp
  tags: ['router','r']
  strategy: free
  tasks:
    - name: Backup Router
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-router backup'
      
- name: Message Processor
  hosts: mp,rmp
  tags: ['mp']
  strategy: free
  tasks:
    - name: Backup Message Processor
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-message-processor backup'
      
- name: Qpid
  hosts: qpid
  tags: ['qpid']
  strategy: free
  tasks:
    - name: Backup Qpid
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service apigee-qpidd backup'
    - name: Backup Qpid Server
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-qpid-server backup'
      
- name: Postgres
  hosts: pg
  tags: ['pg']
  strategy: free
  tasks:
    - name: Backup Postgres
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service apigee-postgresql backup'
    - name: Backup Postgres Server
      become: yes
      command: '/opt/apigee/apigee-service/bin/apigee-service edge-postgres-server backup'