---
- name: Create virtual hosts
  hosts: ms[0]
  gather_facts: no
  vars:
    org: opdk
    env: test
    keystore_name: ks-name
    keystore_alias: alias
    reference_name: ref-name
    file_key: server.key
    file_crt: server.crt
    property_folders:
    - "~/.apigee-secure"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-settings-region }
  - { role: apigee-opdk-settings-private-address }
  - { role: apigee-opdk-settings-management-server }
  
  tasks:
  - name: POST Create KeyStore
    shell: 'curl -X POST "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org }}/e/{{ env }}/keystores" \
                --header "Content-Type: application/json" \
                -u {{ opdk_user_email }}:{{ opdk_user_pass }} \
                -d "{\"name\" : \"{{ keystore_name }}\"}"'
    delegate_to: 127.0.0.1

  - name: POST Create KeyStore
    shell: 'curl -X POST "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org }}/e/{{ env }}/keystores/{{ keystore_name }}/aliases?alias={{ keystore_alias }}&format=keycertfile" \
                -u {{ opdk_user_email }}:{{ opdk_user_pass }} \
                -F "keyFile=@{{ file_key }}" -F "certFile=@{{ file_crt }}"'
    delegate_to: 127.0.0.1

  - name: POST Create KeyStore
    shell: 'curl -X POST "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org }}/e/{{ env }}/references" \
                --header "Content-Type: application/json" \
                -u {{ opdk_user_email }}:{{ opdk_user_pass }} \
                -d "{\"name\":\"fif-ref\",\"refers\":\"{{ keystore_name }}\",\"resourceType\":\"KeyStore\"}"'
    delegate_to: 127.0.0.1