---
- name: Playbook to remove a cassandra
  hosts: "{{ target_hosts }}"
  gather_facts: no

  vars:
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
    component_name: "edge-router"

  roles:
  - { role: apigee-opdk-modules, tags: ['minimum', 'config'] }
  - { role: apigee-opdk-server-self, server_types: ['router'] }

  tasks:
  - name: Set attributes if available
    set_fact:
      uuid: "{{ edge_router_self.uUID }}"
      pod: "{{ edge_router_self.pod }}"

  - name: Assert variables exist
    assert:
      that:
      - region is defined and region | trim | length > 0
      - pod is defined and pod | trim | length > 0
      - uuid is defined and uuid | trim | length > 0
      - opdk_user_email is defined
      - opdk_user_pass is defined
      msg: "Please provide the missing attribute"

  - name: Register Router
    uri:
      url: "http://{{ local_mgmt_ip }}:8080/v1/regions/{{ region_name }}/pods/{{ pod }}/servers"
      method: POST
      user: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'
      body_format: 'form-urlencoded'
      body:
        uuid: '{{ uuid }}'
        type: 'router'
        action: 'add'

