---
- name: Update Planet Cache and Bootstrap
  hosts: planet
  tags: ['os']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules, tags: ['minimum', 'config', 'pgmaster-config'] }
    - { role: apigee-opdk-setup-os-epel, tags: ['epel'] }
    - { role: apigee-opdk-shutdown-iptables, tags: ['minimum', 'iptables'] }
    - { role: apigee-opdk-yum-repository-proxy-config, tags: ['yum-proxy-config']}
    - { role: apigee-opdk-setup-os-minimum, tags: ['os-minimum'] }
    - { role: apigee-opdk-setup-os-limits, tags: ['limit'] }
    - { role: apigee-opdk-setup-os-sysctl, tags: ['sysctl'] }
    - { role: apigee-opdk-setup-selinux-disable, tags: ['minimum', 'selinux'] }
    - { role: apigee-server-restart, tags: ['minimum', 'restart-server'], start_check_delay: 30, when: (selinux_disabled is defined and selinux_disabled.changed) or (iptables_disabled is defined and not iptables_disabled) or (force_restart is defined and force_restart)  }
    - { role: apigee-opdk-setup-os-common, tags: ['os-common'] }
    - { role: apigee-opdk-settings-private-address, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-management-server, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-ldap, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-region, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-cassandra, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-postgres, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-setup-apigee-user, tags: ['minimum', 'apigee-user', 'bootstrap'] }
    - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['minimum', 'apigee-user', 'bootstrap'] }
    - { role: apigee-opdk-setup-openjdk, tags: ['minimum', 'openjdk'], jdk_version: '1.8' }
    - { role: apigee-opdk-setup-java-home, tags: ['minimum', 'java-home', 'bootstrap'] }
    - { role: apigee-opdk-setup-bootstrap, tags: ['minimum', 'apigee-bootstrap', 'bootstrap'] }
    - { role: apigee-opdk-setup-license, tags: ['minimum', 'license', 'bootstrap'] }
    - { role: apigee-opdk-setup-component-install, component: 'apigee-setup', tags: ['minimum', 'setup', 'apigee-component-install', 'apigee-pre-req','common-install', 'common'] }
    - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['minimum', 'apigee-user','ownership', 'apigee-pre-req','common-install', 'common'] }


- name: Add Postgres Standby servers beyond one
  hosts: pgmaster
  tags: ['master']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules, tags: ['minimum', 'config', 'pgmaster-config'] }
  tasks:
    - name: Clear old postgresql.properties file
      become: true
      file:
        path: '/opt/apigee/customer/application/postgresql.properties'
        state: 'absent'

    - name: Setup replication variable
      set_fact:
        replication_string: ''

    - name: Create replication string
      set_fact:
        replication_string: "{{ replication_string }}host     replication     apigee {{ hostvars[item]['private_address'] }}/32     trust\n"
      with_items: "{{ groups['pgstandby'] }}"

    - name: Prepare properties
      import_role:
        name: apigee-opdk-cwc-update
      vars:
        cwc_properties:
          - { key: 'conf_pg_hba_replication.connection', value: '{{ replication_string }}', file_name: 'postgresql' }

    - name: Stop pgmaster
      import_role:
        name: apigee-opdk-stop-components
      vars:
        component_name: "apigee-postgresql"

    - name: Start pgmaster
      import_role:
        name: apigee-opdk-start-components
      vars:
        component_name: "apigee-postgresql"


- name: Configure & Install Postgres
  hosts: "{{ target_hosts }}"
  serial: 1
  gather_facts: no
  tags: ['pg','pgstandby', 'analytics']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules, tags: ['minimum', 'config', 'pg-config'] }
    - { role: apigee-opdk-setup-silent-installation-config, tags: ['minimum', 'config', 'pg-config']  }
    - { role: apigee-opdk-setup-component, profile: 'ps', tags: ['minimum', 'pg-setup'] }
    - { role: apigee-opdk-setup-postgres-config, clear_pgdata: True, tags: ['minimum', 'pgstandby-config'] }
    - { role: apigee-opdk-setup-postgres-standby, tags: ['minimum', 'pgstandby-setup'] }
    - { role: apigee-opdk-stop-components, tags: ['pgstandby-start', 'start'] }
    - { role: apigee-opdk-start-components, tags: ['pgstandby-start', 'start'] }
    - { role: apigee-opdk-setup-status, tags: ['pgstandby-status','status']  }
