---
- name: Collect Configuration Information for Planet
  hosts: ms[0]
  gather_facts: no
  vars:
    org: opdk
    env: test
    uuid: xxxx-xxxx-xx-xxx-xxxxx
    region: dc-1
    pod: gateway
    property_folders:
    - "~/.apigee-secure"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-settings-region }
  - { role: apigee-opdk-settings-private-address }
  - { role: apigee-opdk-settings-management-server }

  tasks:
  - name: Deregister Message Processor from the organization's environments
    uri:
      url: "http://{{ local_mgmt_ip }}:8080/v1/o/{{ org }}/e/{{ env }}/servers"
      method: POST
      user: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'
      body_format: 'form-urlencoded'
      body:
        uuid: '{{ uuid }}'
        action: 'remove'
        pod: "{{ pod_name }}"
        region: "{{ region }}"