---
- name: Collect Configuration Information for Planet
  hosts: edge
  strategy: free
  tags: ['cache']
  vars:
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup','common','expansion'] }
    - { role: apigee-opdk-settings-private-address, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-management-server, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-region, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }

- name: Alert Apigee component Monit for Platform
  hosts: edge
  tags: ['all']
  strategy: free
  vars:
    opdk_alert_mail_from: ''
    opdk_alert_mail_send_1: ''
  roles:
    - apigee-opdk-setup-monit-alert