---
- name: Configure & Install Cassandra & Zookeeper
  hosts: ds
  gather_facts: no
  serial: 1
  tags: ['ds']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-setup-component, profile: 'ds' }

- name: Configure & Install Management Server
  hosts: ms
  gather_facts: no
  serial: 1
  tags: ['ms']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-setup-component, profile: 'ms', when: region_num | int < 3 }
    - { role: apigee-opdk-setup-component, profile: 'ms', when: region_num | int> 2, port_timeout: 300 }
    - { role: apigee-opdk-setup-component, profile: 'ui', tags: ['ui'] }

- name: Configure & Install Router and Message Processor
  hosts: rmp
  gather_facts: no
  tags: ['edge','rmp']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-setup-component, profile: 'rmp', tags: ['minimum', 'rmp'] }
    - { role: apigee-opdk-server-self, server_types: ['router'], tags: ['self'] }
    - { role: apigee-opdk-server-self, server_types: ['mp'], tags: ['self'] }
    - { role: apigee-opdk-server-registration-state, username: "{{ opdk_user_email }}", password: "{{ opdk_user_pass }}", server_self: "{{ edge_router_self }}", mgmt_server_ip: "{{ local_mgmt_ip }}", tags: ['self']  }

- name: Configure & Install Router
  hosts: router
  gather_facts: no
  tags: ['router','edge']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-setup-component, profile: 'r', tags: ['minimum', 'router'] }
    - { role: apigee-opdk-server-self, server_types: ['router'], tags: ['self'] }
    - { role: apigee-opdk-server-registration-state, username: "{{ opdk_user_email }}", password: "{{ opdk_user_pass }}", server_self: "{{ edge_router_self }}", mgmt_server_ip: "{{ local_mgmt_ip }}", tags: ['self']  }

- name: Configure & Install Message Processor
  hosts: mp
  gather_facts: no
  tags: ['mp','edge']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-setup-component, profile: 'mp', tags: ['minimum', 'mp'] }
    - { role: apigee-opdk-server-self, server_types: ['mp'], tags: ['self'] }
    - { role: apigee-opdk-server-registration-state, username: "{{ opdk_user_email }}", password: "{{ opdk_user_pass }}", server_self: "{{ edge_mp_self }}", mgmt_server_ip: "{{ local_mgmt_ip }}", tags: ['self']  }

- name: Configure & Install Qpid
  hosts: qpid
  gather_facts: no
  tags: ['qpid','edge','analytics']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-update-component-qpidd }
    - { role: apigee-opdk-setup-component, profile: 'qs', tags: ['minimum', 'qs-setup'] }
    - { role: apigee-opdk-server-self, server_types: ['qs'], tags: ['self'] }


- name: Configure & Install Postgres
  hosts: pgmaster,pgstandby,pg[0]
  serial: 1
  gather_facts: no
  tags: ['pg','edge', 'analytics']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-settings-postgres, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-setup-component, profile: 'ps', tags: ['minimum', 'pg-setup'] }
    - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self'] }

- name: Configure Postgres Master
  hosts: pgmaster
  serial: 1
  gather_facts: no
  tags: ['pgmaster','edge', 'analytics']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-settings-postgres, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-setup-postgres-config, tags: ['minimum', 'config', 'pgmaster-config'] }
    - { role: apigee-opdk-setup-postgres-master, tags: ['minimum', 'pgmaster-setup']  }
    - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self'] }

- name: Configure Postgres Standby
  hosts: pgstandby
  serial: 1
  gather_facts: no
  tags: ['pgstandby','edge', 'analytics']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-settings-postgres, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-stop-components, component_name: 'apigee-postgresql', tags: ['minimum', 'pgstandby-config'] }
    - { role: apigee-opdk-setup-postgres-config, clear_pgdata: True, tags: ['minimum', 'pgstandby-config'] }
    - { role: apigee-opdk-setup-postgres-standby, tags: ['minimum', 'pgstandby-setup'] }

- name: Configure Organization and Environments
  hosts: ms[0]
  serial: 1
  gather_facts: no
  tags: ['org']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-setup-org }

- name: Update for Regions with No Management Server
  hosts: ds
  serial: 1
  tags: ['expansion']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-setup-cassandra-registration, when: region_num > "2", tags: ['cassandra-registration'] }
    - { role: apigee-opdk-cassandra-rebuild, when: region_num > "2", tags: ['cassandra-rebuild']  }


