---
# Ansible Roles for Setting Operating System Requirements
- src: https://github.com/chronos085/apigee-opdk-setup-apigee-user.git

- src: https://github.com/chronos085/apigee-opdk-setup-apigee-user-ownership.git

- src: https://github.com/chronos085/apigee-opdk-setup-os-common.git

- src: https://github.com/chronos085/apigee-opdk-setup-os-minimum.git

- src: https://github.com/chronos085/apigee-opdk-setup-os-limits.git

- src: https://github.com/chronos085/apigee-opdk-setup-os-epel.git

- src: https://github.com/chronos085/apigee-opdk-setup-os-sysctl.git

- src: https://github.com/chronos085/apigee-opdk-setup-os-postgres.git

- src: https://github.com/chronos085/apigee-opdk-setup-os-pip.git

- src: https://github.com/chronos085/apigee-opdk-setup-os-openldap.git

- src: https://github.com/chronos085/apigee-opdk-setup-openjdk.git

- src: https://github.com/chronos085/apigee-opdk-setup-openjdk-cache.git

- src: https://github.com/chronos085/apigee-opdk-setup-selinux-disable.git

- src: https://github.com/chronos085/apigee-opdk-shutdown-iptables.git

- src: https://github.com/chronos085/apigee-opdk-yum-repository-proxy-config.git

- src: https://github.com/chronos085/apigee-opdk-yum-packages.git

- src: https://github.com/chronos085/apigee-server-restart.git


# Ansible Roles for Bootstrap Installation and Setup
- src: https://github.com/chronos085/apigee-opdk-setup-bootstrap.git

- src: https://github.com/chronos085/apigee-opdk-setup-bootstrap-cache.git

- src: https://github.com/chronos085/apigee-opdk-setup-bootstrap-archive-installer.git

- src: https://github.com/chronos085/apigee-opdk-setup-component-install.git


# Ansible Roles for Component Installation and Setup
- src: https://github.com/chronos085/apigee-opdk-setup-silent-installation-config.git

- src: https://github.com/chronos085/apigee-opdk-setup-component.git

- src: https://github.com/chronos085/apigee-opdk-setup-component-installer.git

- src: https://github.com/chronos085/apigee-opdk-setup-java-home.git

- src: https://github.com/chronos085/apigee-opdk-setup-postgres-config.git

- src: https://github.com/chronos085/apigee-opdk-setup-postgres-master.git

- src: https://github.com/chronos085/apigee-opdk-setup-postgres-standby.git

- src: https://github.com/chronos085/apigee-opdk-setup-status.git

- src: https://github.com/chronos085/apigee-opdk-modules.git

- src: https://github.com/chronos085/apigee-opdk-server-self.git

- src: https://github.com/chronos085/apigee-opdk-start-components.git

- src: https://github.com/chronos085/apigee-opdk-stop-components.git

- src: https://github.com/chronos085/apigee-opdk-setup-license.git

- src: https://github.com/chronos085/apigee-opdk-settings-ldap.git

- src: https://github.com/chronos085/apigee-opdk-settings-management-server.git

- src: https://github.com/chronos085/apigee-opdk-settings-postgres.git

- src: https://github.com/chronos085/apigee-opdk-settings-private-address.git

- src: https://github.com/chronos085/apigee-opdk-settings-cassandra.git

- src: https://github.com/chronos085/apigee-opdk-settings-region.git

- src: https://github.com/chronos085/apigee-opdk-setup-scopes-add.git

- src: https://github.com/chronos085/apigee-opdk-server-registration-state.git

- src: https://github.com/chronos085/apigee-opdk-setup-cassandra-registration.git

- src: https://github.com/chronos085/apigee-opdk-cassandra-rebuild.git
