---
- src: https://github.com/chronos085/apigee-opdk-backup.git

- src: https://github.com/chronos085/apigee-opdk-start-components.git

- src: https://github.com/chronos085/apigee-opdk-stop-components.git

- src: https://github.com/chronos085/apigee-opdk-setup-bootstrap-rollback.git

- src: https://github.com/chronos085/apigee-opdk-setup-postgres-remove.git

- src: https://github.com/chronos085/apigee-opdk-setup-qpid-remove.git

- src: https://github.com/chronos085/apigee-opdk-setup-scopes-remove.git

- src: https://github.com/chronos085/apigee-opdk-setup-axgroup-remove.git

- src: https://github.com/chronos085/apigee-opdk-server-self.git

- src: https://github.com/chronos085/apigee-opdk-modules.git

- src: https://github.com/chronos085/apigee-opdk-settings-private-address.git

- src: https://github.com/chronos085/apigee-opdk-settings-management-server.git

- src: https://github.com/chronos085/apigee-opdk-settings-ldap.git

- src: https://github.com/chronos085/apigee-opdk-settings-region.git

- src: https://github.com/chronos085/apigee-opdk-settings-cassandra.git

- src: https://github.com/chronos085/apigee-opdk-settings-postgres.git

