---
- name: Collect Configuration Information for Planet
  hosts: edge
  strategy: free
  tags: ['cache']
  vars:
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup','common','expansion'] }
    - { role: apigee-opdk-settings-private-address, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-management-server, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-region, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }

- name: Alert Apigee component Monit for Cassandra & Zookeeper
  hosts: ds
  tags: ['ds','zk']
  strategy: free
  vars:
    opdk_alert_mail_from: ''
    opdk_alert_mail_send_1: ''
  roles:
    - apigee-opdk-setup-monit-alert
     
- name: Alert Apigee component Monit for LDAP
  hosts: ldap
  tags: ['ldap']
  strategy: free
  vars:
    opdk_alert_mail_from: ''
    opdk_alert_mail_send_1: ''
  roles:
    - apigee-opdk-setup-monit-alert

- name: Alert Apigee component Monit for Management Server
  hosts: ms
  tags: ['ms']
  strategy: free
  vars:
    opdk_alert_mail_from: ''
    opdk_alert_mail_send_1: ''
  roles:
    - apigee-opdk-setup-monit-alert
      
- name: Alert Apigee component Monit for Edge-UI
  hosts: ui
  tags: ['ui']
  strategy: free
  vars:
    opdk_alert_mail_from: ''
    opdk_alert_mail_send_1: ''
  roles:
    - apigee-opdk-setup-monit-alert
      
- name: Alert Apigee component Monit for Router
  hosts: router,rmp
  tags: ['router','r']
  strategy: free
  vars:
    opdk_alert_mail_from: ''
    opdk_alert_mail_send_1: ''
  roles:
    - apigee-opdk-setup-monit-alert
      
- name: Alert Apigee component Monit for Message Processor
  hosts: mp,rmp
  tags: ['mp']
  strategy: free
  vars:
    opdk_alert_mail_from: ''
    opdk_alert_mail_send_1: ''
  roles:
    - apigee-opdk-setup-monit-alert
      
- name: Alert Apigee component Monit for Qpid
  hosts: qpid
  tags: ['qpid']
  strategy: free
  vars:
    opdk_alert_mail_from: ''
    opdk_alert_mail_send_1: ''
  roles:
    - apigee-opdk-setup-monit-alert
      
- name: Alert Apigee component Monit for Postgres
  hosts: pg
  tags: ['pg']
  strategy: free
  vars:
    opdk_alert_mail_from: ''
    opdk_alert_mail_send_1: ''
  roles:
    - apigee-opdk-setup-monit-alert