---
- src: https://github.com/carlosfrias/apigee-opdk-setup-scopes-state.git

- src: https://github.com/carlosfrias/apigee-opdk-server-self.git

- src: https://github.com/carlosfrias/apigee-opdk-server-registration-state.git

- src: https://github.com/carlosfrias/apigee-opdk-modules.git
