---
- name: Configure & Install Router and Message Processor
  hosts: rmp
  gather_facts: no
  tags: ['edge','rmp']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - apigee-opdk-modules
    - { role: apigee-opdk-setup-component, profile: 'rmp', tags: ['minimum', 'rmp'] }
    - { role: apigee-opdk-server-self, server_types: ['router'], tags: ['self'] }
    - { role: apigee-opdk-server-self, server_types: ['mp'], tags: ['self'] }
    - { role: apigee-opdk-server-registration-state, username: "{{ opdk_user_email }}", password: "{{ opdk_user_pass }}", server_self: "{{ edge_router_self }}", mgmt_server_ip: "{{ local_mgmt_ip }}", tags: ['self']  }