---
- name: Collect Edge Installation Attributes
  import_playbook: collect-attributes.yml
  tags: ['cache']

- name: Download apigee mirror archive
  tags: ['download']
  hosts: "{{ target_hosts }}"
  gather_facts: no
  vars:
    local_apigee_path: ~/.apigee
    property_folders:
    - "~/.apigee-secure"
    - "{{ local_apigee_path }}"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-setup-bootstrap-download-archive }
