---
- name: Expose apigee mirror web server
  tags: ['nginx']
  hosts: "{{ target_hosts }}"
  vars:
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-setup-mirror-nginx, tags: ['nginx'] }
