---
- name: Collect Edge Installation Attributes
  import_playbook: collect-attributes.yml
  tags: ['cache']

- name: Upload apigee mirror archive
  hosts: "{{ target_hosts }}"
  tags: ['upload']
  vars:
    apigee_home: "/opt/apigee"
    local_apigee_path: "~/.apigee"
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-setup-apigee-user, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-bootstrap-upload-archive, tags: ['upload'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user', 'bootstrap'] }
