---
- name: Router
  hosts: router,rmp
  tags: ['router','r']
  strategy: free
  roles:
    - apigee-opdk-setup-node-uninstall
      
- name: Message Processor
  hosts: mp,rmp
  tags: ['mp']
  strategy: free
  roles:
    - apigee-opdk-setup-node-uninstall

- name: Qpid
  hosts: qpid
  tags: ['qpid']
  strategy: free
  roles:
    - apigee-opdk-setup-node-uninstall
      
- name: Postgres
  hosts: pg
  tags: ['pg']
  strategy: free
  roles:
    - apigee-opdk-setup-node-uninstall

- name: Edge-UI
  hosts: ui
  tags: ['ui']
  strategy: free
  roles:
    - apigee-opdk-setup-node-uninstall

- name: Ldap
  hosts: ldap
  tags: ['ldap']
  strategy: free
  roles:
    - apigee-opdk-setup-node-uninstall

- name: Management Server
  hosts: ms
  tags: ['ms']
  strategy: free
  roles:
    - apigee-opdk-setup-node-uninstall

- name: Cassandra & Zookeeper
  hosts: ds
  tags: ['ds','zk']
  strategy: free
  roles:
    - apigee-opdk-setup-node-uninstall